language: node_js
node_js:
  - "8"
install:
  - yarn
script:
  - yarn test
cache:
  directories:
    - ~/.yarn
    - ~/.nvm
sudo: required # https://github.com/travis-ci/travis-ci/issues/8836#issuecomment-348227535
addons:
  chrome: stable
